# Generated by Django 3.1.3 on 2021-02-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_url', models.TextField(null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_payments', to='ledger.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_payments', to='ledger.account')),
            ],
        ),
    ]
