# Generated by Django 3.1.5 on 2021-01-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
