# Generated by Django 3.1.3 on 2021-09-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20210908_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saving_key',
            field=models.CharField(default=None, max_length=56, null=True, unique=True),
        ),
    ]
