---
- name: configure user accounts
  tags: [system]
  block:
    - name: create groups
      group:
        name: "{{ item.username }}"
        state: present
      with_items: "{{ users }}"

    - name: create users
      user:
        name: "{{ item.username }}"
        group: "{{ item.username }}"
        groups:
          - admin
          - sudo
        append: yes
        generate_ssh_key: no
        create_home: yes
        shell: /bin/bash
        state: present
      with_items: "{{ users }}"

    - name: create ssh directories
      file:
        path: /home/{{ item.username }}/.ssh
        group: "{{ item.username }}"
        owner: "{{ item.username }}"
        state: directory
        mode: 0755
      with_items: "{{ users }}"

    - name: set authorized keys
      copy:
        content: "{{ item.public_key }}"
        dest: /home/{{ item.username }}/.ssh/authorized_keys
        group: "{{ item.username }}"
        owner: "{{ item.username }}"
        mode: 0600
      with_items: "{{ users }}"

    - name: passwordless sudoers
      copy:
        dest: /etc/sudoers.d/{{ item.username }}
        content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
        mode: 0440
      with_items: "{{ users }}"
